nodeLinker: pnp
pnpMode: strict
pnpFallbackMode: none
pnpEnableInlining: false
enableGlobalCache: false
compressionLevel: 0
enableScripts: false

packageExtensions:
  "@crab-dev/rc-alert@*": &crabRuntime
    dependencies:
      "@crab-dev/css": "0.1.23"
      "@types/react": "^19.2.18"
      "lucide-react": "^1.23.0"
      "react": "19.2.8"
      "react-dom": "19.2.8"
  "@crab-dev/rc-button@*": *crabRuntime
  "@crab-dev/rc-card@*": *crabRuntime
  "@crab-dev/rc-checkbox@*": *crabRuntime
  "@crab-dev/rc-dialog@*": *crabRuntime
  "@crab-dev/rc-drawer@*": *crabRuntime
  "@crab-dev/rc-dropdown-container@*": *crabRuntime
  "@crab-dev/rc-empty@*": *crabRuntime
  "@crab-dev/rc-hooks@*": *crabRuntime
  "@crab-dev/rc-line-edit@*": *crabRuntime
  "@crab-dev/rc-number-edit@*": *crabRuntime
  "@crab-dev/rc-prose@*": *crabRuntime
  "@crab-dev/rc-segmented@*": *crabRuntime
  "@crab-dev/rc-select@*": *crabRuntime
  "@crab-dev/rc-skeleton@*": *crabRuntime
  "@crab-dev/rc-spin@*": *crabRuntime
  "@crab-dev/rc-switch@*": *crabRuntime
  "@crab-dev/rc-tag@*": *crabRuntime
  "@crab-dev/rc-text-edit@*": *crabRuntime
  "@crab-dev/rc-token-global@*": *crabRuntime
  "@crab-dev/rc-token-semantic@*": *crabRuntime
  "@crab-dev/rc-tooltip@*": *crabRuntime
  "@crab-dev/rc-tree@*": *crabRuntime
  "@crab-dev/rc-virtual@*": *crabRuntime
  "lucide-react@*":
    dependencies:
      "@types/react": "^19.2.18"
