[package]
name = "wake_ecma_parser"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "语法分析器（递归下降 + Pratt，一遍产出依赖）。DESIGN §4.4"

[lints]
workspace = true

[dependencies]
wake_common.workspace = true
wake_ecma_ast.workspace = true
wake_ecma_lexer.workspace = true
wake_ecma_semantic.workspace = true
wake_ecma_transform.workspace = true
bumpalo.workspace = true

[dev-dependencies]
insta.workspace = true
criterion.workspace = true

[[bench]]
name = "parser"
harness = false
