[package]
name = "wake_ecma_semantic"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "独立 ECMAScript 作用域、符号与引用分析，供 parser、minifier 和 bundler 复用。"

[lints]
workspace = true

[dependencies]
wake_common.workspace = true
wake_ecma_ast.workspace = true
