declare const classNameBrand: unique symbol
declare const keyframesNameBrand: unique symbol
declare const cssVarBrand: unique symbol

/** A class name generated by Wake's CSS compiler. */
export type ClassName = string & {
  readonly [classNameBrand]: true
}

/** A keyframes identifier generated by Wake's CSS compiler. */
export type KeyframesName = string & {
  readonly [keyframesNameBrand]: true
}

/** A `var(--custom-property)` reference that can be interpolated directly. */
export type CSSVar = `var(--${string})` & {
  readonly [cssVarBrand]: true
}

export type CSSInterpolation =
  | string
  | number
  | false
  | null
  | undefined
  | ClassName
  | KeyframesName
  | CSSVar

export type ClassDictionary = Readonly<Record<string, unknown>>

export type ClassValue =
  | string
  | false
  | null
  | undefined
  | 0
  | ClassDictionary
  | readonly ClassValue[]

export type CSSVariableStyles = Record<string, string | number>

/**
 * Declares a scoped class. Wake replaces this template tag with a ClassName
 * and extracts its CSS during compilation.
 */
export declare function css(
  strings: TemplateStringsArray,
  ...interpolations: readonly CSSInterpolation[]
): ClassName

/** Combines strings, conditional objects, and arbitrarily nested arrays. */
export declare function cx(...values: readonly ClassValue[]): ClassName

/**
 * Declares scoped keyframes. Wake replaces this template tag with a
 * KeyframesName and extracts its CSS during compilation.
 */
export declare function keyframes(
  strings: TemplateStringsArray,
  ...interpolations: readonly CSSInterpolation[]
): KeyframesName

/**
 * Declares complete global CSS rules, such as `:root { ... }`. Wake extracts
 * the rules during compilation.
 */
export declare function globalStyle(
  strings: TemplateStringsArray,
  ...interpolations: readonly CSSInterpolation[]
): void

/** Creates a realm-unique `var(--custom-property)` reference. */
export declare function createVar(debugName?: string): CSSVar

/** Converts CSS variable references to custom-property keys for inline styles. */
export declare function assignVars(
  variables: Readonly<Record<CSSVar, string | number>>,
): CSSVariableStyles
